services:
  pythonapp:
    build:
      context: ./python_app
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      traefik:
      srdnlen-website-internal:
    depends_on:
      - srdnlen-website-ghost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.srdnlen.entrypoints=https"
      - "traefik.http.routers.srdnlen.tls=true"
      - "traefik.http.routers.srdnlen.tls.certresolver=cloudflare"
      - "traefik.http.routers.srdnlen.rule=HostRegexp(`${SRDNLEN_WEBSITE_DOMAIN}`)" # (www\\.)?srdnlen.it}`)"

  srdnlen-website-ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: srdnlen-website-db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:2368
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      # NODE_ENV: development
    networks:
      srdnlen-website-internal:
    depends_on:
      srdnlen-website-db:
        condition: service_healthy
    volumes:
      - data:/var/lib/ghost/content
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.ghosttestingwebsite.entrypoints=https"
    #  - "traefik.http.routers.ghosttestingwebsite.tls=true"
    #  - "traefik.http.routers.ghosttestingwebsite.tls.certresolver=cloudflare"
    #  - "traefik.http.routers.ghosttestingwebsite.rule=Host(`ghosttestingwebsite.chall.srdnlen.it`)"

  srdnlen-website-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
    volumes:
      - db:/var/lib/mysql
    networks:
      srdnlen-website-internal:

volumes:
  data:
  db:

networks:
  traefik:
    external: true
  srdnlen-website-internal:
